name: db-api
channels:
        - conda-forge
dependencies:
        - flask-restx
        - flask
        - flask_cors
        - gevent
        - gunicorn
        - marshmallow
        - pip
        - psycopg2
        - sqlalchemy<2.0.4
        - pytest
        - python=3.9
        - redis-py
        - werkzeug=2.1.2
        - pip:
                - pytest-cov
                - pgvector
                - tox-conda
                - git+https://github.com/korbit-ai/python-config-probe.git

