name: db-api
channels:
        - conda-forge
dependencies:
        - flask-restx
        - flask
        - flask_cors
        - gevent
        - gunicorn
        - langchain
        - marshmallow
        - pip
        - psycopg2
        - sqlalchemy<2.0.4
        - pytest
        - python=3.9
        - werkzeug=2.1.2
        - pip:
                - config-probe
                - pytest-cov
                - pgvector
                - tox-conda

