version: '3.6'
services:

  exercise_hint:
    image: korbit/exercise_hint:v1
    build:
      context: ../../.
      dockerfile: Dockerfile
    container_name: exercise_hint
    restart: always

    hostname: exercise_hint

    deploy:
       mode: replicated
       replicas: 1

    ports:
      - 9016:80

    environment:
      TEST: test
